/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATA_H_RPCGEN
#define _DATA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum result_t {
	RESULT_INT = 1,
	RESULT_DOUBLE = 2,
};
typedef enum result_t result_t;

struct union_arg {
	result_t result;
	union {
		int intval;
		double doubleval;
	} union_arg_u;
};
typedef struct union_arg union_arg;

struct data {
	short short_arg;
	long long_arg;
	char *vstring_arg;
	char fopaque_arg[3];
	struct {
		u_int vopaque_arg_len;
		char *vopaque_arg_val;
	} vopaque_arg;
	short fshort_arg[4];
	struct {
		u_int vlong_arg_len;
		long *vlong_arg_val;
	} vlong_arg;
	union_arg uarg;
};
typedef struct data data;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_result_t (XDR *, result_t*);
extern  bool_t xdr_union_arg (XDR *, union_arg*);
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_result_t ();
extern bool_t xdr_union_arg ();
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATA_H_RPCGEN */
