/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "data.h"

bool_t
xdr_result_t (XDR *xdrs, result_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_union_arg (XDR *xdrs, union_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_result_t (xdrs, &objp->result))
		 return FALSE;
	switch (objp->result) {
	case RESULT_INT:
		 if (!xdr_int (xdrs, &objp->union_arg_u.intval))
			 return FALSE;
		break;
	case RESULT_DOUBLE:
		 if (!xdr_double (xdrs, &objp->union_arg_u.doubleval))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_short (xdrs, &objp->short_arg))
			 return FALSE;
		 if (!xdr_long (xdrs, &objp->long_arg))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->vstring_arg, 128))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->fopaque_arg, 3))
			 return FALSE;
		 if (!xdr_bytes (xdrs, (char **)&objp->vopaque_arg.vopaque_arg_val, (u_int *) &objp->vopaque_arg.vopaque_arg_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( 4 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->fshort_arg, 4,
				sizeof (short), (xdrproc_t) xdr_short))
				 return FALSE;

		} else {
		{
			register short *genp;

			for (i = 0, genp = objp->fshort_arg;
				i < 4; ++i) {
				IXDR_PUT_SHORT(buf, *genp++);
			}
		}
		}
		 if (!xdr_array (xdrs, (char **)&objp->vlong_arg.vlong_arg_val, (u_int *) &objp->vlong_arg.vlong_arg_len, ~0,
			sizeof (long), (xdrproc_t) xdr_long))
			 return FALSE;
		 if (!xdr_union_arg (xdrs, &objp->uarg))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_short (xdrs, &objp->short_arg))
			 return FALSE;
		 if (!xdr_long (xdrs, &objp->long_arg))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->vstring_arg, 128))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->fopaque_arg, 3))
			 return FALSE;
		 if (!xdr_bytes (xdrs, (char **)&objp->vopaque_arg.vopaque_arg_val, (u_int *) &objp->vopaque_arg.vopaque_arg_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( 4 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->fshort_arg, 4,
				sizeof (short), (xdrproc_t) xdr_short))
				 return FALSE;

		} else {
		{
			register short *genp;

			for (i = 0, genp = objp->fshort_arg;
				i < 4; ++i) {
				*genp++ = IXDR_GET_SHORT(buf);
			}
		}
		}
		 if (!xdr_array (xdrs, (char **)&objp->vlong_arg.vlong_arg_val, (u_int *) &objp->vlong_arg.vlong_arg_len, ~0,
			sizeof (long), (xdrproc_t) xdr_long))
			 return FALSE;
		 if (!xdr_union_arg (xdrs, &objp->uarg))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_short (xdrs, &objp->short_arg))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->long_arg))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->vstring_arg, 128))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->fopaque_arg, 3))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->vopaque_arg.vopaque_arg_val, (u_int *) &objp->vopaque_arg.vopaque_arg_len, ~0))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fshort_arg, 4,
		sizeof (short), (xdrproc_t) xdr_short))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->vlong_arg.vlong_arg_val, (u_int *) &objp->vlong_arg.vlong_arg_len, ~0,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	 if (!xdr_union_arg (xdrs, &objp->uarg))
		 return FALSE;
	return TRUE;
}
