#include	"test.h"		/* generated by rpcgen */
static int count = 1;

void test_RPCwrapper(int size, char* buf){

  CLIENT* cl;
  test_in in;
  test_out *outp;
  struct timeval tv;

  cl = clnt_create("127.0.0.1", TEST_PROG, TEST_VERS, "TCP");

  


   in.arg2 = buf;


  if ( (outp = testproc_1(&in, cl)) == NULL){
    printf("outp is NULL!\n");
    clnt_destroy(cl);	 
    err_quit("%s", clnt_sperror(cl, 2));
  }
  

  //  outp = testproc_1(&in, cl);


  printf("testRPCwrapper %d!\n", count++);
  clnt_destroy(cl);
//  printf("result: %ld\n", outp->res1);
}

void user(int times, int size) {
  int i = 0;
  char* buf = (char*)malloc(size+1);
  
  for(i = 0; i < size; i++) {
    buf[i] = (i%10) + '0';
  }
  buf[size] = '\0';

  for(i = 0; i < times; i++) {
    test_RPCwrapper(size,buf);
  }
  printf("user end!\n");

  printf("%s\n", buf);

  free(buf);
}

int pseduo_main(int argc, char** argv) {
  if(argc != 3) {
    printf("Incorrect command-line arguments!\n");
    return 1;
  } 
  else {
    int times = atoi(argv[1]);
    int size = atoi(argv[2]);
    user(times,size);
    return 0;
  }
}

int
main(int argc, char **argv)
{
  if (argc != 3)
    err_quit("usage: client <hostname> <integer-value>");

  pseduo_main(argc, argv);

  exit(0);
}
