/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct test_in {
	int arg1;
	char *arg2;
};
typedef struct test_in test_in;

struct test_out {
	long res1;
};
typedef struct test_out test_out;

#define TEST_PROG 0x31230000
#define TEST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TESTPROC 1
extern  test_out * testproc_1(test_in *, CLIENT *);
extern  test_out * testproc_1_svc(test_in *, struct svc_req *);
extern int test_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TESTPROC 1
extern  test_out * testproc_1();
extern  test_out * testproc_1_svc();
extern int test_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_test_in (XDR *, test_in*);
extern  bool_t xdr_test_out (XDR *, test_out*);

#else /* K&R C */
extern bool_t xdr_test_in ();
extern bool_t xdr_test_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
