/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "data.h"
#include <floatingpoint.h> /* required under Solaris 2.6 */

bool_t
xdr_color (XDR *xdrs, color *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_union_arg (XDR *xdrs, union_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case 0:
		 if (!xdr_int (xdrs, &objp->union_arg_u.intval))
			 return FALSE;
		break;
	case 1:
		 if (!xdr_float (xdrs, &objp->union_arg_u.floatval))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_square_in (XDR *xdrs, square_in *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_char (xdrs, &objp->char_arg))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_short (xdrs, &objp->short_arg))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->int_arg))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->long_arg))
				 return FALSE;

		} else {
		IXDR_PUT_SHORT(buf, objp->short_arg);
		IXDR_PUT_LONG(buf, objp->int_arg);
		IXDR_PUT_LONG(buf, objp->long_arg);
		}
		 if (!xdr_quad_t (xdrs, &objp->hyper_arg))
			 return FALSE;
		 if (!xdr_u_char (xdrs, &objp->uchar_arg))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_short (xdrs, &objp->ushort_arg))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->uint_arg))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->ulong_arg))
				 return FALSE;

		} else {
		IXDR_PUT_U_SHORT(buf, objp->ushort_arg);
		IXDR_PUT_U_LONG(buf, objp->uint_arg);
		IXDR_PUT_U_LONG(buf, objp->ulong_arg);
		}
		 if (!xdr_u_quad_t (xdrs, &objp->uhyper_arg))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->float_arg))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->double_arg))
			 return FALSE;
		 if (!xdr_quadruple (xdrs, &objp->quad_arg))
			 return FALSE;
		 if (!xdr_bool (xdrs, &objp->bool_arg))
			 return FALSE;
		 if (!xdr_color (xdrs, &objp->color_arg))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->vstring_arg, 5))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->fopaque_arg, 10))
			 return FALSE;
		 if (!xdr_bytes (xdrs, (char **)&objp->vopaque_arg.vopaque_arg_val, (u_int *) &objp->vopaque_arg.vopaque_arg_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( 4 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->fshort_arg, 4,
				sizeof (short), (xdrproc_t) xdr_short))
				 return FALSE;

		} else {
		{
			register short *genp;

			for (i = 0, genp = objp->fshort_arg;
				i < 4; ++i) {
				IXDR_PUT_SHORT(buf, *genp++);
			}
		}
		}
		 if (!xdr_array (xdrs, (char **)&objp->vshort_arg.vshort_arg_val, (u_int *) &objp->vshort_arg.vshort_arg_len, ~0,
			sizeof (long), (xdrproc_t) xdr_long))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_char (xdrs, &objp->char_arg))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_short (xdrs, &objp->short_arg))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->int_arg))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->long_arg))
				 return FALSE;

		} else {
		objp->short_arg = IXDR_GET_SHORT(buf);
		objp->int_arg = IXDR_GET_LONG(buf);
		objp->long_arg = IXDR_GET_LONG(buf);
		}
		 if (!xdr_quad_t (xdrs, &objp->hyper_arg))
			 return FALSE;
		 if (!xdr_u_char (xdrs, &objp->uchar_arg))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_short (xdrs, &objp->ushort_arg))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->uint_arg))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->ulong_arg))
				 return FALSE;

		} else {
		objp->ushort_arg = IXDR_GET_U_SHORT(buf);
		objp->uint_arg = IXDR_GET_U_LONG(buf);
		objp->ulong_arg = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_u_quad_t (xdrs, &objp->uhyper_arg))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->float_arg))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->double_arg))
			 return FALSE;
		 if (!xdr_quadruple (xdrs, &objp->quad_arg))
			 return FALSE;
		 if (!xdr_bool (xdrs, &objp->bool_arg))
			 return FALSE;
		 if (!xdr_color (xdrs, &objp->color_arg))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->vstring_arg, 5))
			 return FALSE;
		 if (!xdr_opaque (xdrs, objp->fopaque_arg, 10))
			 return FALSE;
		 if (!xdr_bytes (xdrs, (char **)&objp->vopaque_arg.vopaque_arg_val, (u_int *) &objp->vopaque_arg.vopaque_arg_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( 4 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->fshort_arg, 4,
				sizeof (short), (xdrproc_t) xdr_short))
				 return FALSE;

		} else {
		{
			register short *genp;

			for (i = 0, genp = objp->fshort_arg;
				i < 4; ++i) {
				*genp++ = IXDR_GET_SHORT(buf);
			}
		}
		}
		 if (!xdr_array (xdrs, (char **)&objp->vshort_arg.vshort_arg_val, (u_int *) &objp->vshort_arg.vshort_arg_len, ~0,
			sizeof (long), (xdrproc_t) xdr_long))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_char (xdrs, &objp->char_arg))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->short_arg))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->int_arg))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->long_arg))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->hyper_arg))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->uchar_arg))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->ushort_arg))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->uint_arg))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->ulong_arg))
		 return FALSE;
	 if (!xdr_u_quad_t (xdrs, &objp->uhyper_arg))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->float_arg))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->double_arg))
		 return FALSE;
	 if (!xdr_quadruple (xdrs, &objp->quad_arg))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->bool_arg))
		 return FALSE;
	 if (!xdr_color (xdrs, &objp->color_arg))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->vstring_arg, 5))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->fopaque_arg, 10))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->vopaque_arg.vopaque_arg_val, (u_int *) &objp->vopaque_arg.vopaque_arg_len, ~0))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fshort_arg, 4,
		sizeof (short), (xdrproc_t) xdr_short))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->vshort_arg.vshort_arg_val, (u_int *) &objp->vshort_arg.vshort_arg_len, ~0,
		sizeof (long), (xdrproc_t) xdr_long))
		 return FALSE;
	return TRUE;
}
